import {IRepo} from "../interfaces/repo";
import {IRepoOwner} from "../interfaces/repo-owner";
import {RepoOwner} from "./repo-owner";
import {IRepoPermission} from "../interfaces/repo-permission";
import {RepoPermission} from "./repo-permission";

export class Repo implements IRepo {
  allow_forking: boolean = false;
  archive_url: string = '';
  archived: boolean = false;
  assignees_url: string = '';
  blobs_url: string = '';
  branches_url: string = '';
  clone_url: string = '';
  collaborators_url: string = '';
  comments_url: string = '';
  commits_url: string = '';
  compare_url: string = '';
  contents_url: string = '';
  contributors_url: string = '';
  created_at: Date = new Date();
  default_branch: string = '';
  deployments_url: string = '';
  description: any;
  disabled: boolean = false;
  downloads_url: string = '';
  events_url: string = '';
  fork: boolean = false;
  forks: number = 0;
  forks_count: number = 0;
  forks_url: string = '';
  full_name: string = '';
  git_commits_url: string = '';
  git_refs_url: string = '';
  git_tags_url: string = '';
  git_url: string = '';
  has_discussions: boolean = false;
  has_downloads: boolean = false;
  has_issues: boolean = false;
  has_pages: boolean = false;
  has_projects: boolean = false;
  has_wiki: boolean = false;
  homepage: any;
  hooks_url: string = '';
  html_url: string = '';
  id: number = 0;
  is_template: boolean = false;
  issue_comment_url: string = '';
  issue_events_url: string = '';
  issues_url: string = '';
  keys_url: string = '';
  labels_url: string = '';
  language: string = '';
  languages_url: string = '';
  license: any;
  merges_url: string = '';
  milestones_url: string = '';
  mirror_url: any;
  name: string = '';
  node_id: string = '';
  notifications_url: string = '';
  open_issues: number = 0;
  open_issues_count: number = 0;
  owner: IRepoOwner = new RepoOwner();
  permissions: IRepoPermission = new RepoPermission();
  private: boolean = false;
  pulls_url: string = '';
  pushed_at: Date = new Date();
  releases_url: string = '';
  size: number = 0;
  ssh_url: string = '';
  stargazers_count: number = 0;
  stargazers_url: string = '';
  statuses_url: string = '';
  subscribers_url: string = '';
  subscription_url: string = '';
  svn_url: string = '';
  tags_url: string = '';
  teams_url: string = '';
  topics: string[] = [];
  trees_url: string = '';
  updated_at: Date = new Date();
  url: string = '';
  visibility: string = '';
  watchers: number = 0;
  watchers_count: number = 0;
  web_commit_signoff_required: boolean = false;

  constructor(repo?: IRepo | undefined) {
    if (repo) {
      this.allow_forking = repo.allow_forking;
      this.archive_url = repo.archive_url;
      this.archived = repo.archived;
      this.assignees_url = repo.assignees_url;
      this.blobs_url = repo.blobs_url;
      this.branches_url = repo.branches_url;
      this.clone_url = repo.clone_url;
      this.collaborators_url = repo.collaborators_url;
      this.comments_url = repo.comments_url;
      this.commits_url = repo.commits_url;
      this.compare_url = repo.compare_url;
      this.contents_url = repo.contents_url;
      this.contributors_url = repo.contributors_url;
      this.created_at = repo.created_at;
      this.default_branch = repo.default_branch;
      this.deployments_url = repo.deployments_url;
      this.description = repo.description;
      this.disabled = repo.disabled;
      this.downloads_url = repo.downloads_url;
      this.events_url = repo.events_url;
      this.fork = repo.fork;
      this.forks = repo.forks;
      this.forks_count = repo.forks_count;
      this.forks_url = repo.forks_url;
      this.full_name = repo.full_name;
      this.git_commits_url = repo.git_commits_url;
      this.git_refs_url = repo.git_refs_url;
      this.git_tags_url = repo.git_tags_url;
      this.git_url = repo.git_url;
      this.has_discussions = repo.has_discussions;
      this.has_downloads = repo.has_downloads;
      this.has_issues = repo.has_issues;
      this.has_pages = repo.has_pages;
      this.has_projects = repo.has_projects;
      this.has_wiki = repo.has_wiki;
      this.homepage = repo.homepage;
      this.hooks_url = repo.hooks_url;
      this.html_url = repo.html_url;
      this.id = repo.id;
      this.is_template = repo.is_template;
      this.issue_comment_url = repo.issue_comment_url;
      this.issue_events_url = repo.issue_events_url;
      this.issues_url = repo.issues_url;
      this.keys_url = repo.keys_url;
      this.labels_url = repo.labels_url;
      this.language = repo.language;
      this.languages_url = repo.languages_url;
      this.license = repo.license;
      this.merges_url = repo.merges_url;
      this.milestones_url = repo.milestones_url;
      this.mirror_url = repo.mirror_url;
      this.name = repo.name;
      this.node_id = repo.node_id;
      this.notifications_url = repo.notifications_url;
      this.open_issues = repo.open_issues;
      this.open_issues_count = repo.open_issues_count;
      this.owner = repo.owner;
      this.permissions = repo.permissions;
      this.private = repo.private;
      this.pulls_url = repo.pulls_url;
      this.pushed_at = repo.pushed_at;
      this.releases_url = repo.releases_url;
      this.size = repo.size;
      this.ssh_url = repo.ssh_url;
      this.stargazers_count = repo.stargazers_count;
      this.stargazers_url = repo.stargazers_url;
      this.statuses_url = repo.statuses_url;
      this.subscribers_url = repo.subscribers_url;
      this.subscription_url = repo.subscription_url;
      this.svn_url = repo.svn_url;
      this.tags_url = repo.tags_url;
      this.teams_url = repo.teams_url;
      this.topics = repo.topics;
      this.trees_url = repo.trees_url;
      this.updated_at = repo.updated_at;
      this.url = repo.url;
      this.visibility = repo.visibility;
      this.watchers = repo.watchers;
      this.watchers_count = repo.watchers_count;
      this.web_commit_signoff_required = repo.web_commit_signoff_required;
    }
  }


  // Method to convert the current class to a flat object
  toJSON(): IRepo {
    return Object.assign({}, this);
  }

}
