import {DevelopmentLanguageColor} from '../interfaces/development-language-color';

export const DevelopmentLanguageColors: DevelopmentLanguageColor[] = [
  {
    color: `#814CCC`,
    name: `1C Enterprise`,
    url: `https://github.com/trending?l=1C-Enterprise`
  }, {
    color: `#38761D`,
    name: `2-Dimensional Array`,
    url: `https://github.com/trending?l=2-Dimensional-Array`
  }, {
    color: `#004289`,
    name: `4D`,
    url: `https://github.com/trending?l=4D`
  }, {
    color: `#E8274B`,
    name: `ABAP`,
    url: `https://github.com/trending?l=ABAP`
  }, {
    color: `#555e25`,
    name: `ABAP CDS`,
    url: `https://github.com/trending?l=ABAP-CDS`
  }, {
    color: `#882B0F`,
    name: `ActionScript`,
    url: `https://github.com/trending?l=ActionScript`
  }, {
    color: `#02f88c`,
    name: `Ada`,
    url: `https://github.com/trending?l=Ada`
  }, {
    color: `#800000`,
    name: `Adblock Filter List`,
    url: `https://github.com/trending?l=Adblock-Filter-List`
  }, {
    color: `#fa0f00`,
    name: `Adobe Font Metrics`,
    url: `https://github.com/trending?l=Adobe-Font-Metrics`
  }, {
    color: `#315665`,
    name: `Agda`,
    url: `https://github.com/trending?l=Agda`
  }, {
    color: `#B9D9FF`,
    name: `AGS Script`,
    url: `https://github.com/trending?l=AGS-Script`
  }, {
    color: `#34EB6B`,
    name: `AIDL`,
    url: `https://github.com/trending?l=AIDL`
  }, {
    color: `#3AA2B5`,
    name: `AL`,
    url: `https://github.com/trending?l=AL`
  }, {
    color: `#64C800`,
    name: `Alloy`,
    url: `https://github.com/trending?l=Alloy`
  }, {
    color: `#0D597F`,
    name: `Alpine Abuild`,
    url: `https://github.com/trending?l=Alpine-Abuild`
  }, {
    color: `#A89663`,
    name: `Altium Designer`,
    url: `https://github.com/trending?l=Altium-Designer`
  }, {
    color: `#E6EFBB`,
    name: `AMPL`,
    url: `https://github.com/trending?l=AMPL`
  }, {
    color: `#C7D7DC`,
    name: `AngelScript`,
    url: `https://github.com/trending?l=AngelScript`
  }, {
    color: `#A9157E`,
    name: `Ant Build System`,
    url: `https://github.com/trending?l=Ant-Build-System`
  }, {
    color: `#ff269e`,
    name: `Antlers`,
    url: `https://github.com/trending?l=Antlers`
  }, {
    color: `#9DC3FF`,
    name: `ANTLR`,
    url: `https://github.com/trending?l=ANTLR`
  }, {
    color: `#d12127`,
    name: `ApacheConf`,
    url: `https://github.com/trending?l=ApacheConf`
  }, {
    color: `#1797c0`,
    name: `Apex`,
    url: `https://github.com/trending?l=Apex`
  }, {
    color: `#2ACCA8`,
    name: `API Blueprint`,
    url: `https://github.com/trending?l=API-Blueprint`
  }, {
    color: `#5A8164`,
    name: `APL`,
    url: `https://github.com/trending?l=APL`
  }, {
    color: `#0B3D91`,
    name: `Apollo Guidance Computer`,
    url: `https://github.com/trending?l=Apollo-Guidance-Computer`
  }, {
    color: `#101F1F`,
    name: `AppleScript`,
    url: `https://github.com/trending?l=AppleScript`
  }, {
    color: `#aa2afe`,
    name: `Arc`,
    url: `https://github.com/trending?l=Arc`
  }, {
    color: `#73a0c5`,
    name: `AsciiDoc`,
    url: `https://github.com/trending?l=AsciiDoc`
  }, {
    color: '#778899',
    name: `ASL`,
    url: `https://github.com/trending?l=ASL`
  }, {
    color: `#9400ff`,
    name: `ASP.NET`,
    url: `https://github.com/trending?l=ASP.NET`
  }, {
    color: `#a957b0`,
    name: `AspectJ`,
    url: `https://github.com/trending?l=AspectJ`
  }, {
    color: `#6E4C13`,
    name: `Assembly`,
    url: `https://github.com/trending?l=Assembly`
  }, {
    color: `#ff5a03`,
    name: `Astro`,
    url: `https://github.com/trending?l=Astro`
  }, {
    color: `#ff0000`,
    name: `Asymptote`,
    url: `https://github.com/trending?l=Asymptote`
  }, {
    color: `#1ac620`,
    name: `ATS`,
    url: `https://github.com/trending?l=ATS`
  }, {
    color: `#9CC134`,
    name: `Augeas`,
    url: `https://github.com/trending?l=Augeas`
  }, {
    color: `#6594b9`,
    name: `AutoHotkey`,
    url: `https://github.com/trending?l=AutoHotkey`
  }, {
    color: `#1C3552`,
    name: `AutoIt`,
    url: `https://github.com/trending?l=AutoIt`
  }, {
    color: `#0040FF`,
    name: `Avro IDL`,
    url: `https://github.com/trending?l=Avro-IDL`
  }, {
    color: `#c30e9b`,
    name: `Awk`,
    url: `https://github.com/trending?l=Awk`
  }, {
    color: `#FF5000`,
    name: `Ballerina`,
    url: `https://github.com/trending?l=Ballerina`
  }, {
    color: `#ff0000`,
    name: `BASIC`,
    url: `https://github.com/trending?l=BASIC`
  }, {
    color: `#C1F12E`,
    name: `Batchfile`,
    url: `https://github.com/trending?l=Batchfile`
  }, {
    color: `#a52f4e`,
    name: `Beef`,
    url: `https://github.com/trending?l=Beef`
  }, {
    color: '#778899',
    name: `Befunge`,
    url: `https://github.com/trending?l=Befunge`
  }, {
    color: `#15A13C`,
    name: `Berry`,
    url: `https://github.com/trending?l=Berry`
  }, {
    color: `#778899`,
    name: `BibTeX`,
    url: `https://github.com/trending?l=BibTeX`
  }, {
    color: `#519aba`,
    name: `Bicep`,
    url: `https://github.com/trending?l=Bicep`
  }, {
    color: `#5562ac`,
    name: `Bikeshed`,
    url: `https://github.com/trending?l=Bikeshed`
  }, {
    color: `#6A463F`,
    name: `Bison`,
    url: `https://github.com/trending?l=Bison`
  }, {
    color: `#00bce4`,
    name: `BitBake`,
    url: `https://github.com/trending?l=BitBake`
  }, {
    color: `#f7523f`,
    name: `Blade`,
    url: `https://github.com/trending?l=Blade`
  }, {
    color: `#00FFAE`,
    name: `BlitzBasic`,
    url: `https://github.com/trending?l=BlitzBasic`
  }, {
    color: `#cd6400`,
    name: `BlitzMax`,
    url: `https://github.com/trending?l=BlitzMax`
  }, {
    color: `#12223c`,
    name: `Bluespec`,
    url: `https://github.com/trending?l=Bluespec`
  }, {
    color: `#d4bec1`,
    name: `Boo`,
    url: `https://github.com/trending?l=Boo`
  }, {
    color: `#c80fa0`,
    name: `Boogie`,
    url: `https://github.com/trending?l=Boogie`
  }, {
    color: `#2F2530`,
    name: `Brainfuck`,
    url: `https://github.com/trending?l=Brainfuck`
  }, {
    color: `#66AABB`,
    name: `BrighterScript`,
    url: `https://github.com/trending?l=BrighterScript`
  }, {
    color: `#662D91`,
    name: `Brightscript`,
    url: `https://github.com/trending?l=Brightscript`
  }, {
    color: `#ffd539`,
    name: `Browserslist`,
    url: `https://github.com/trending?l=Browserslist`
  }, {
    color: `#555555`,
    name: `C`,
    url: `https://github.com/trending?l=C`
  }, {
    color: `#178600`,
    name: `C#`,
    url: `https://github.com/trending?l=Csharp`
  }, {
    color: `#f34b7d`,
    name: `C++`,
    url: `https://github.com/trending?l=C++`
  }, {
    color: '#778899',
    name: `C2hs Haskell`,
    url: `https://github.com/trending?l=C2hs-Haskell`
  }, {
    color: `#483465`,
    name: `Cabal Config`,
    url: `https://github.com/trending?l=Cabal-Config`
  }, {
    color: `#00ef8b`,
    name: `Cadence`,
    url: `https://github.com/trending?l=Cadence`
  }, {
    color: `#ff4a48`,
    name: `Cairo`,
    url: `https://github.com/trending?l=Cairo`
  }, {
    color: `#3be133`,
    name: `CameLIGO`,
    url: `https://github.com/trending?l=CameLIGO`
  }, {
    color: `#0092d1`,
    name: `CAP CDS`,
    url: `https://github.com/trending?l=CAP-CDS`
  }, {
    color: `#c42727`,
    name: `Cap'n Proto`,
    url: `https://github.com/trending?l=Cap'n-Proto`
  }, {
    color: '#778899',
    name: `CartoCSS`,
    url: `https://github.com/trending?l=CartoCSS`
  }, {
    color: `#dfa535`,
    name: `Ceylon`,
    url: `https://github.com/trending?l=Ceylon`
  }, {
    color: `#8dc63f`,
    name: `Chapel`,
    url: `https://github.com/trending?l=Chapel`
  }, {
    color: '#778899',
    name: `Charity`,
    url: `https://github.com/trending?l=Charity`
  }, {
    color: `#3f8000`,
    name: `ChucK`,
    url: `https://github.com/trending?l=ChucK`
  }, {
    color: `#707575`,
    name: `Circom`,
    url: `https://github.com/trending?l=Circom`
  }, {
    color: `#ccccff`,
    name: `Cirru`,
    url: `https://github.com/trending?l=Cirru`
  }, {
    color: `#db901e`,
    name: `Clarion`,
    url: `https://github.com/trending?l=Clarion`
  }, {
    color: `#5546ff`,
    name: `Clarity`,
    url: `https://github.com/trending?l=Clarity`
  }, {
    color: `#6a40fd`,
    name: `Classic ASP`,
    url: `https://github.com/trending?l=Classic-ASP`
  }, {
    color: `#3F85AF`,
    name: `Clean`,
    url: `https://github.com/trending?l=Clean`
  }, {
    color: `#E4E6F3`,
    name: `Click`,
    url: `https://github.com/trending?l=Click`
  }, {
    color: `#00A300`,
    name: `CLIPS`,
    url: `https://github.com/trending?l=CLIPS`
  }, {
    color: `#db5855`,
    name: `Clojure`,
    url: `https://github.com/trending?l=Clojure`
  }, {
    color: `#0d948f`,
    name: `Closure Templates`,
    url: `https://github.com/trending?l=Closure-Templates`
  }, {
    color: `#FFA000`,
    name: `Cloud Firestore Security Rules`,
    url: `https://github.com/trending?l=Cloud-Firestore-Security-Rules`
  }, {
    color: `#DA3434`,
    name: `CMake`,
    url: `https://github.com/trending?l=CMake`
  }, {
    color: '#778899',
    name: `COBOL`,
    url: `https://github.com/trending?l=COBOL`
  }, {
    color: `#140f46`,
    name: `CodeQL`,
    url: `https://github.com/trending?l=CodeQL`
  }, {
    color: `#244776`,
    name: `CoffeeScript`,
    url: `https://github.com/trending?l=CoffeeScript`
  }, {
    color: `#ed2cd6`,
    name: `ColdFusion`,
    url: `https://github.com/trending?l=ColdFusion`
  }, {
    color: `#ed2cd6`,
    name: `ColdFusion CFC`,
    url: `https://github.com/trending?l=ColdFusion-CFC`
  }, {
    color: `#F1A42B`,
    name: `COLLADA`,
    url: `https://github.com/trending?l=COLLADA`
  }, {
    color: `#3fb68b`,
    name: `Common Lisp`,
    url: `https://github.com/trending?l=Common-Lisp`
  }, {
    color: `#B5314C`,
    name: `Common Workflow Language`,
    url: `https://github.com/trending?l=Common-Workflow-Language`
  }, {
    color: `#B0CE4E`,
    name: `Component Pascal`,
    url: `https://github.com/trending?l=Component-Pascal`
  }, {
    color: '#778899',
    name: `Cool`,
    url: `https://github.com/trending?l=Cool`
  }, {
    color: `#d0b68c`,
    name: `Coq`,
    url: `https://github.com/trending?l=Coq`
  }, {
    color: `#000100`,
    name: `Crystal`,
    url: `https://github.com/trending?l=Crystal`
  }, {
    color: `#244776`,
    name: `CSON`,
    url: `https://github.com/trending?l=CSON`
  }, {
    color: `#1a1a1a`,
    name: `Csound`,
    url: `https://github.com/trending?l=Csound`
  }, {
    color: `#1a1a1a`,
    name: `Csound Document`,
    url: `https://github.com/trending?l=Csound-Document`
  }, {
    color: `#1a1a1a`,
    name: `Csound Score`,
    url: `https://github.com/trending?l=Csound-Score`
  }, {
    color: `#563d7c`,
    name: `CSS`,
    url: `https://github.com/trending?l=CSS`
  }, {
    color: `#237346`,
    name: `CSV`,
    url: `https://github.com/trending?l=CSV`
  }, {
    color: `#3A4E3A`,
    name: `Cuda`,
    url: `https://github.com/trending?l=Cuda`
  }, {
    color: `#5886E1`,
    name: `CUE`,
    url: `https://github.com/trending?l=CUE`
  }, {
    color: `#531242`,
    name: `Curry`,
    url: `https://github.com/trending?l=Curry`
  }, {
    color: `#00007a`,
    name: `CWeb`,
    url: `https://github.com/trending?l=CWeb`
  }, {
    color: '#778899',
    name: `Cycript`,
    url: `https://github.com/trending?l=Cycript`
  }, {
    color: `#34c0eb`,
    name: `Cypher`,
    url: `https://github.com/trending?l=Cypher`
  }, {
    color: `#fedf5b`,
    name: `Cython`,
    url: `https://github.com/trending?l=Cython`
  }, {
    color: `#ba595e`,
    name: `D`,
    url: `https://github.com/trending?l=D`
  }, {
    color: `#FFEC25`,
    name: `Dafny`,
    url: `https://github.com/trending?l=Dafny`
  }, {
    color: `#8eff23`,
    name: `Darcs Patch`,
    url: `https://github.com/trending?l=Darcs-Patch`
  }, {
    color: `#00B4AB`,
    name: `Dart`,
    url: `https://github.com/trending?l=Dart`
  }, {
    color: `#003a52`,
    name: `DataWeave`,
    url: `https://github.com/trending?l=DataWeave`
  }, {
    color: `#D70751`,
    name: `Debian Package Control File`,
    url: `https://github.com/trending?l=Debian-Package-Control-File`
  }, {
    color: `#FBEE96`,
    name: `DenizenScript`,
    url: `https://github.com/trending?l=DenizenScript`
  }, {
    color: `#dfafff`,
    name: `Dhall`,
    url: `https://github.com/trending?l=Dhall`
  }, {
    color: '#778899',
    name: `DIGITAL Command Language`,
    url: `https://github.com/trending?l=DIGITAL-Command-Language`
  }, {
    color: `#aace60`,
    name: `DirectX 3D File`,
    url: `https://github.com/trending?l=DirectX-3D-File`
  }, {
    color: `#447265`,
    name: `DM`,
    url: `https://github.com/trending?l=DM`
  }, {
    color: `#384d54`,
    name: `Dockerfile`,
    url: `https://github.com/trending?l=Dockerfile`
  }, {
    color: `#cca760`,
    name: `Dogescript`,
    url: `https://github.com/trending?l=Dogescript`
  }, {
    color: `#e5d559`,
    name: `Dotenv`,
    url: `https://github.com/trending?l=Dotenv`
  }, {
    color: '#778899',
    name: `DTrace`,
    url: `https://github.com/trending?l=DTrace`
  }, {
    color: `#6c616e`,
    name: `Dylan`,
    url: `https://github.com/trending?l=Dylan`
  }, {
    color: `#ccce35`,
    name: `E`,
    url: `https://github.com/trending?l=E`
  }, {
    color: `#2af0ff`,
    name: `Earthly`,
    url: `https://github.com/trending?l=Earthly`
  }, {
    color: `#069406`,
    name: `Easybuild`,
    url: `https://github.com/trending?l=Easybuild`
  }, {
    color: `#913960`,
    name: `eC`,
    url: `https://github.com/trending?l=eC`
  }, {
    color: `#913960`,
    name: `Ecere Projects`,
    url: `https://github.com/trending?l=Ecere-Projects`
  }, {
    color: `#8a1267`,
    name: `ECL`,
    url: `https://github.com/trending?l=ECL`
  }, {
    color: `#001d9d`,
    name: `ECLiPSe`,
    url: `https://github.com/trending?l=ECLiPSe`
  }, {
    color: `#eb8131`,
    name: `Ecmarkup`,
    url: `https://github.com/trending?l=Ecmarkup`
  }, {
    color: `#fff1f2`,
    name: `EditorConfig`,
    url: `https://github.com/trending?l=EditorConfig`
  }, {
    color: `#4d6977`,
    name: `Eiffel`,
    url: `https://github.com/trending?l=Eiffel`
  }, {
    color: `#a91e50`,
    name: `EJS`,
    url: `https://github.com/trending?l=EJS`
  }, {
    color: `#6e4a7e`,
    name: `Elixir`,
    url: `https://github.com/trending?l=Elixir`
  }, {
    color: `#60B5CC`,
    name: `Elm`,
    url: `https://github.com/trending?l=Elm`
  }, {
    color: `#55BB55`,
    name: `Elvish`,
    url: `https://github.com/trending?l=Elvish`
  }, {
    color: `#c065db`,
    name: `Emacs Lisp`,
    url: `https://github.com/trending?l=Emacs-Lisp`
  }, {
    color: `#FFF4F3`,
    name: `EmberScript`,
    url: `https://github.com/trending?l=EmberScript`
  }, {
    color: `#a78649`,
    name: `EQ`,
    url: `https://github.com/trending?l=EQ`
  }, {
    color: `#B83998`,
    name: `Erlang`,
    url: `https://github.com/trending?l=Erlang`
  }, {
    color: `#FF790B`,
    name: `Euphoria`,
    url: `https://github.com/trending?l=Euphoria`
  }, {
    color: `#b845fc`,
    name: `F#`,
    url: `https://github.com/trending?l=Fsharp`
  }, {
    color: `#572e30`,
    name: `F*`,
    url: `https://github.com/trending?l=F*`
  }, {
    color: `#636746`,
    name: `Factor`,
    url: `https://github.com/trending?l=Factor`
  }, {
    color: `#7b9db4`,
    name: `Fancy`,
    url: `https://github.com/trending?l=Fancy`
  }, {
    color: `#14253c`,
    name: `Fantom`,
    url: `https://github.com/trending?l=Fantom`
  }, {
    color: `#c37240`,
    name: `Faust`,
    url: `https://github.com/trending?l=Faust`
  }, {
    color: `#fff3d7`,
    name: `Fennel`,
    url: `https://github.com/trending?l=Fennel`
  }, {
    color: `#FFDDBB`,
    name: `FIGlet Font`,
    url: `https://github.com/trending?l=FIGlet-Font`
  }, {
    color: `#F6B900`,
    name: `Filebench WML`,
    url: `https://github.com/trending?l=Filebench-WML`
  }, {
    color: '#778899',
    name: `Filterscript`,
    url: `https://github.com/trending?l=Filterscript`
  }, {
    color: `#4aae47`,
    name: `fish`,
    url: `https://github.com/trending?l=fish`
  }, {
    color: `#ffcc33`,
    name: `Fluent`,
    url: `https://github.com/trending?l=Fluent`
  }, {
    color: `#88ccff`,
    name: `FLUX`,
    url: `https://github.com/trending?l=FLUX`
  }, {
    color: `#341708`,
    name: `Forth`,
    url: `https://github.com/trending?l=Forth`
  }, {
    color: `#4d41b1`,
    name: `Fortran`,
    url: `https://github.com/trending?l=Fortran`
  }, {
    color: `#4d41b1`,
    name: `Fortran Free Form`,
    url: `https://github.com/trending?l=Fortran-Free-Form`
  }, {
    color: `#141AC9`,
    name: `FreeBasic`,
    url: `https://github.com/trending?l=FreeBasic`
  }, {
    color: `#0050b2`,
    name: `FreeMarker`,
    url: `https://github.com/trending?l=FreeMarker`
  }, {
    color: `#00cafe`,
    name: `Frege`,
    url: `https://github.com/trending?l=Frege`
  }, {
    color: `#5f021f`,
    name: `Futhark`,
    url: `https://github.com/trending?l=Futhark`
  }, {
    color: `#D08CF2`,
    name: `G-code`,
    url: `https://github.com/trending?l=G-code`
  }, {
    color: `#71b417`,
    name: `Game Maker Language`,
    url: `https://github.com/trending?l=Game-Maker-Language`
  }, {
    color: `#FFC766`,
    name: `GAML`,
    url: `https://github.com/trending?l=GAML`
  }, {
    color: `#f49a22`,
    name: `GAMS`,
    url: `https://github.com/trending?l=GAMS`
  }, {
    color: `#0000cc`,
    name: `GAP`,
    url: `https://github.com/trending?l=GAP`
  }, {
    color: `#FFCFAB`,
    name: `GCC Machine Description`,
    url: `https://github.com/trending?l=GCC-Machine-Description`
  }, {
    color: '#778899',
    name: `GDB`,
    url: `https://github.com/trending?l=GDB`
  }, {
    color: `#355570`,
    name: `GDScript`,
    url: `https://github.com/trending?l=GDScript`
  }, {
    color: `#003058`,
    name: `GEDCOM`,
    url: `https://github.com/trending?l=GEDCOM`
  }, {
    color: `#701516`,
    name: `Gemfile.lock`,
    url: `https://github.com/trending?l=Gemfile.lock`
  }, {
    color: `#ff6900`,
    name: `Gemini`,
    url: `https://github.com/trending?l=Gemini`
  }, {
    color: `#63408e`,
    name: `Genero`,
    url: `https://github.com/trending?l=Genero`
  }, {
    color: `#d8df39`,
    name: `Genero Forms`,
    url: `https://github.com/trending?l=Genero-Forms`
  }, {
    color: `#fb855d`,
    name: `Genie`,
    url: `https://github.com/trending?l=Genie`
  }, {
    color: `#951531`,
    name: `Genshi`,
    url: `https://github.com/trending?l=Genshi`
  }, {
    color: `#9400ff`,
    name: `Gentoo Ebuild`,
    url: `https://github.com/trending?l=Gentoo-Ebuild`
  }, {
    color: `#9400ff`,
    name: `Gentoo Eclass`,
    url: `https://github.com/trending?l=Gentoo-Eclass`
  }, {
    color: `#d20b00`,
    name: `Gerber Image`,
    url: `https://github.com/trending?l=Gerber-Image`
  }, {
    color: `#5B2063`,
    name: `Gherkin`,
    url: `https://github.com/trending?l=Gherkin`
  }, {
    color: `#F44D27`,
    name: `Git Attributes`,
    url: `https://github.com/trending?l=Git-Attributes`
  }, {
    color: `#F44D27`,
    name: `Git Config`,
    url: `https://github.com/trending?l=Git-Config`
  }, {
    color: `#F44D27`,
    name: `Git Revision List`,
    url: `https://github.com/trending?l=Git-Revision-List`
  }, {
    color: `#ffaff3`,
    name: `Gleam`,
    url: `https://github.com/trending?l=Gleam`
  }, {
    color: `#5686a5`,
    name: `GLSL`,
    url: `https://github.com/trending?l=GLSL`
  }, {
    color: `#c1ac7f`,
    name: `Glyph`,
    url: `https://github.com/trending?l=Glyph`
  }, {
    color: `#f0a9f0`,
    name: `Gnuplot`,
    url: `https://github.com/trending?l=Gnuplot`
  }, {
    color: `#00ADD8`,
    name: `Go`,
    url: `https://github.com/trending?l=Go`
  }, {
    color: `#00ADD8`,
    name: `Go Checksums`,
    url: `https://github.com/trending?l=Go-Checksums`
  }, {
    color: `#00ADD8`,
    name: `Go Module`,
    url: `https://github.com/trending?l=Go-Module`
  }, {
    color: `#355570`,
    name: `Godot Resource`,
    url: `https://github.com/trending?l=Godot-Resource`
  }, {
    color: `#88562A`,
    name: `Golo`,
    url: `https://github.com/trending?l=Golo`
  }, {
    color: `#82937f`,
    name: `Gosu`,
    url: `https://github.com/trending?l=Gosu`
  }, {
    color: `#615f8b`,
    name: `Grace`,
    url: `https://github.com/trending?l=Grace`
  }, {
    color: `#02303a`,
    name: `Gradle`,
    url: `https://github.com/trending?l=Gradle`
  }, {
    color: `#ff0000`,
    name: `Grammatical Framework`,
    url: `https://github.com/trending?l=Grammatical-Framework`
  }, {
    color: `#e10098`,
    name: `GraphQL`,
    url: `https://github.com/trending?l=GraphQL`
  }, {
    color: `#2596be`,
    name: `Graphviz (DOT)`,
    url: `https://github.com/trending?l=Graphviz-(DOT)`
  }, {
    color: `#4298b8`,
    name: `Groovy`,
    url: `https://github.com/trending?l=Groovy`
  }, {
    color: `#4298b8`,
    name: `Groovy Server Pages`,
    url: `https://github.com/trending?l=Groovy-Server-Pages`
  }, {
    color: `#FF6800`,
    name: `GSC`,
    url: `https://github.com/trending?l=GSC`
  }, {
    color: `#878787`,
    name: `Hack`,
    url: `https://github.com/trending?l=Hack`
  }, {
    color: `#ece2a9`,
    name: `Haml`,
    url: `https://github.com/trending?l=Haml`
  }, {
    color: `#f7931e`,
    name: `Handlebars`,
    url: `https://github.com/trending?l=Handlebars`
  }, {
    color: `#106da9`,
    name: `HAProxy`,
    url: `https://github.com/trending?l=HAProxy`
  }, {
    color: `#0e60e3`,
    name: `Harbour`,
    url: `https://github.com/trending?l=Harbour`
  }, {
    color: `#5e5086`,
    name: `Haskell`,
    url: `https://github.com/trending?l=Haskell`
  }, {
    color: `#df7900`,
    name: `Haxe`,
    url: `https://github.com/trending?l=Haxe`
  }, {
    color: `#844FBA`,
    name: `HCL`,
    url: `https://github.com/trending?l=HCL`
  }, {
    color: `#dce200`,
    name: `HiveQL`,
    url: `https://github.com/trending?l=HiveQL`
  }, {
    color: `#aace60`,
    name: `HLSL`,
    url: `https://github.com/trending?l=HLSL`
  }, {
    color: `#9ff8ee`,
    name: `HOCON`,
    url: `https://github.com/trending?l=HOCON`
  }, {
    color: `#ffefaf`,
    name: `HolyC`,
    url: `https://github.com/trending?l=HolyC`
  }, {
    color: `#00b171`,
    name: `hoon`,
    url: `https://github.com/trending?l=hoon`
  }, {
    color: `#e34c26`,
    name: `HTML`,
    url: `https://github.com/trending?l=HTML`
  }, {
    color: `#2e1052`,
    name: `HTML+ECR`,
    url: `https://github.com/trending?l=HTML+ECR`
  }, {
    color: `#6e4a7e`,
    name: `HTML+EEX`,
    url: `https://github.com/trending?l=HTML+EEX`
  }, {
    color: `#701516`,
    name: `HTML+ERB`,
    url: `https://github.com/trending?l=HTML+ERB`
  }, {
    color: `#4f5d95`,
    name: `HTML+PHP`,
    url: `https://github.com/trending?l=HTML+PHP`
  }, {
    color: `#512be4`,
    name: `HTML+Razor`,
    url: `https://github.com/trending?l=HTML+Razor`
  }, {
    color: `#005C9C`,
    name: `HTTP`,
    url: `https://github.com/trending?l=HTTP`
  }, {
    color: `#f68712`,
    name: `HXML`,
    url: `https://github.com/trending?l=HXML`
  }, {
    color: `#7790B2`,
    name: `Hy`,
    url: `https://github.com/trending?l=Hy`
  }, {
    color: '#778899',
    name: `HyPhy`,
    url: `https://github.com/trending?l=HyPhy`
  }, {
    color: `#a3522f`,
    name: `IDL`,
    url: `https://github.com/trending?l=IDL`
  }, {
    color: `#b30000`,
    name: `Idris`,
    url: `https://github.com/trending?l=Idris`
  }, {
    color: `#000000`,
    name: `Ignore List`,
    url: `https://github.com/trending?l=Ignore-List`
  }, {
    color: `#0000cc`,
    name: `IGOR Pro`,
    url: `https://github.com/trending?l=IGOR-Pro`
  }, {
    color: `#99AAFF`,
    name: `ImageJ Macro`,
    url: `https://github.com/trending?l=ImageJ-Macro`
  }, {
    color: `#16cec6`,
    name: `Imba`,
    url: `https://github.com/trending?l=Imba`
  }, {
    color: '#778899',
    name: `Inform 7`,
    url: `https://github.com/trending?l=Inform-7`
  }, {
    color: `#d1dbe0`,
    name: `INI`,
    url: `https://github.com/trending?l=INI`
  }, {
    color: '#778899',
    name: `Ink`,
    url: `https://github.com/trending?l=Ink`
  }, {
    color: `#264b99`,
    name: `Inno Setup`,
    url: `https://github.com/trending?l=Inno-Setup`
  }, {
    color: `#a9188d`,
    name: `Io`,
    url: `https://github.com/trending?l=Io`
  }, {
    color: `#078193`,
    name: `Ioke`,
    url: `https://github.com/trending?l=Ioke`
  }, {
    color: `#FEFE00`,
    name: `Isabelle`,
    url: `https://github.com/trending?l=Isabelle`
  }, {
    color: `#FEFE00`,
    name: `Isabelle ROOT`,
    url: `https://github.com/trending?l=Isabelle-ROOT`
  }, {
    color: `#9EEDFF`,
    name: `J`,
    url: `https://github.com/trending?l=J`
  }, {
    color: `#0886a5`,
    name: `Janet`,
    url: `https://github.com/trending?l=Janet`
  }, {
    color: `#b07219`,
    name: `JAR Manifest`,
    url: `https://github.com/trending?l=JAR-Manifest`
  }, {
    color: `#d03600`,
    name: `Jasmin`,
    url: `https://github.com/trending?l=Jasmin`
  }, {
    color: `#b07219`,
    name: `Java`,
    url: `https://github.com/trending?l=Java`
  }, {
    color: `#2A6277`,
    name: `Java Properties`,
    url: `https://github.com/trending?l=Java-Properties`
  }, {
    color: `#2A6277`,
    name: `Java Server Pages`,
    url: `https://github.com/trending?l=Java-Server-Pages`
  }, {
    color: `#f1e05a`,
    name: `JavaScript`,
    url: `https://github.com/trending?l=JavaScript`
  }, {
    color: `#f1e05a`,
    name: `JavaScript+ERB`,
    url: `https://github.com/trending?l=JavaScript+ERB`
  }, {
    color: `#d90e09`,
    name: `JCL`,
    url: `https://github.com/trending?l=JCL`
  }, {
    color: `#15c213`,
    name: `Jest Snapshot`,
    url: `https://github.com/trending?l=Jest-Snapshot`
  }, {
    color: `#21D789`,
    name: `JetBrains MPS`,
    url: `https://github.com/trending?l=JetBrains-MPS`
  }, {
    color: `#DBCA00`,
    name: `JFlex`,
    url: `https://github.com/trending?l=JFlex`
  }, {
    color: `#a52a22`,
    name: `Jinja`,
    url: `https://github.com/trending?l=Jinja`
  }, {
    color: `#56b3cb`,
    name: `Jison`,
    url: `https://github.com/trending?l=Jison`
  }, {
    color: `#56b3cb`,
    name: `Jison Lex`,
    url: `https://github.com/trending?l=Jison-Lex`
  }, {
    color: `#843179`,
    name: `Jolie`,
    url: `https://github.com/trending?l=Jolie`
  }, {
    color: `#c7254e`,
    name: `jq`,
    url: `https://github.com/trending?l=jq`
  }, {
    color: `#292929`,
    name: `JSON`,
    url: `https://github.com/trending?l=JSON`
  }, {
    color: `#292929`,
    name: `JSON with Comments`,
    url: `https://github.com/trending?l=JSON-with-Comments`
  }, {
    color: `#267CB9`,
    name: `JSON5`,
    url: `https://github.com/trending?l=JSON5`
  }, {
    color: `#40d47e`,
    name: `JSONiq`,
    url: `https://github.com/trending?l=JSONiq`
  }, {
    color: `#0c479c`,
    name: `JSONLD`,
    url: `https://github.com/trending?l=JSONLD`
  }, {
    color: `#0064bd`,
    name: `Jsonnet`,
    url: `https://github.com/trending?l=Jsonnet`
  }, {
    color: `#a270ba`,
    name: `Julia`,
    url: `https://github.com/trending?l=Julia`
  }, {
    color: `#DA5B0B`,
    name: `Jupyter Notebook`,
    url: `https://github.com/trending?l=Jupyter-Notebook`
  }, {
    color: `#384d54`,
    name: `Just`,
    url: `https://github.com/trending?l=Just`
  }, {
    color: `#773b37`,
    name: `Kaitai Struct`,
    url: `https://github.com/trending?l=Kaitai-Struct`
  }, {
    color: `#6f8042`,
    name: `KakouneScript`,
    url: `https://github.com/trending?l=KakouneScript`
  }, {
    color: `#41adf0`,
    name: `KerboScript`,
    url: `https://github.com/trending?l=KerboScript`
  }, {
    color: `#2f4aab`,
    name: `KiCad Layout`,
    url: `https://github.com/trending?l=KiCad-Layout`
  }, {
    color: `#2f4aab`,
    name: `KiCad Legacy Layout`,
    url: `https://github.com/trending?l=KiCad-Legacy-Layout`
  }, {
    color: `#2f4aab`,
    name: `KiCad Schematic`,
    url: `https://github.com/trending?l=KiCad-Schematic`
  }, {
    color: `#A97BFF`,
    name: `Kotlin`,
    url: `https://github.com/trending?l=Kotlin`
  }, {
    color: `#28430A`,
    name: `KRL`,
    url: `https://github.com/trending?l=KRL`
  }, {
    color: `#1da6e0`,
    name: `kvlang`,
    url: `https://github.com/trending?l=kvlang`
  }, {
    color: `#fede06`,
    name: `LabVIEW`,
    url: `https://github.com/trending?l=LabVIEW`
  }, {
    color: `#2980B9`,
    name: `Lark`,
    url: `https://github.com/trending?l=Lark`
  }, {
    color: `#999999`,
    name: `Lasso`,
    url: `https://github.com/trending?l=Lasso`
  }, {
    color: `#f2a542`,
    name: `Latte`,
    url: `https://github.com/trending?l=Latte`
  }, {
    color: '#778899',
    name: `Lean`,
    url: `https://github.com/trending?l=Lean`
  }, {
    color: `#1d365d`,
    name: `Less`,
    url: `https://github.com/trending?l=Less`
  }, {
    color: `#DBCA00`,
    name: `Lex`,
    url: `https://github.com/trending?l=Lex`
  }, {
    color: `#4C3023`,
    name: `LFE`,
    url: `https://github.com/trending?l=LFE`
  }, {
    color: `#0e74ff`,
    name: `LigoLANG`,
    url: `https://github.com/trending?l=LigoLANG`
  }, {
    color: `#9ccc7c`,
    name: `LilyPond`,
    url: `https://github.com/trending?l=LilyPond`
  }, {
    color: '#778899',
    name: `Limbo`,
    url: `https://github.com/trending?l=Limbo`
  }, {
    color: `#67b8de`,
    name: `Liquid`,
    url: `https://github.com/trending?l=Liquid`
  }, {
    color: `#315665`,
    name: `Literate Agda`,
    url: `https://github.com/trending?l=Literate-Agda`
  }, {
    color: `#244776`,
    name: `Literate CoffeeScript`,
    url: `https://github.com/trending?l=Literate-CoffeeScript`
  }, {
    color: `#5e5086`,
    name: `Literate Haskell`,
    url: `https://github.com/trending?l=Literate-Haskell`
  }, {
    color: `#499886`,
    name: `LiveScript`,
    url: `https://github.com/trending?l=LiveScript`
  }, {
    color: `#185619`,
    name: `LLVM`,
    url: `https://github.com/trending?l=LLVM`
  }, {
    color: '#778899',
    name: `Logos`,
    url: `https://github.com/trending?l=Logos`
  }, {
    color: `#295b9a`,
    name: `Logtalk`,
    url: `https://github.com/trending?l=Logtalk`
  }, {
    color: `#cc9900`,
    name: `LOLCODE`,
    url: `https://github.com/trending?l=LOLCODE`
  }, {
    color: `#652B81`,
    name: `LookML`,
    url: `https://github.com/trending?l=LookML`
  }, {
    color: '#778899',
    name: `LoomScript`,
    url: `https://github.com/trending?l=LoomScript`
  }, {
    color: `#3d9970`,
    name: `LSL`,
    url: `https://github.com/trending?l=LSL`
  }, {
    color: `#000080`,
    name: `Lua`,
    url: `https://github.com/trending?l=Lua`
  }, {
    color: '#778899',
    name: `M`,
    url: `https://github.com/trending?l=M`
  }, {
    color: '#778899',
    name: `M4`,
    url: `https://github.com/trending?l=M4`
  }, {
    color: '#778899',
    name: `M4Sugar`,
    url: `https://github.com/trending?l=M4Sugar`
  }, {
    color: `#d8ffff`,
    name: `Macaulay2`,
    url: `https://github.com/trending?l=Macaulay2`
  }, {
    color: `#427819`,
    name: `Makefile`,
    url: `https://github.com/trending?l=Makefile`
  }, {
    color: `#7e858d`,
    name: `Mako`,
    url: `https://github.com/trending?l=Mako`
  }, {
    color: `#083fa1`,
    name: `Markdown`,
    url: `https://github.com/trending?l=Markdown`
  }, {
    color: `#42bff2`,
    name: `Marko`,
    url: `https://github.com/trending?l=Marko`
  }, {
    color: `#f97732`,
    name: `Mask`,
    url: `https://github.com/trending?l=Mask`
  }, {
    color: `#dd1100`,
    name: `Mathematica`,
    url: `https://github.com/trending?l=Mathematica`
  }, {
    color: `#e16737`,
    name: `MATLAB`,
    url: `https://github.com/trending?l=MATLAB`
  }, {
    color: `#c4a79c`,
    name: `Max`,
    url: `https://github.com/trending?l=Max`
  }, {
    color: `#00a6a6`,
    name: `MAXScript`,
    url: `https://github.com/trending?l=MAXScript`
  }, {
    color: `#E22837`,
    name: `mcfunction`,
    url: `https://github.com/trending?l=mcfunction`
  }, {
    color: `#ff2b2b`,
    name: `Mercury`,
    url: `https://github.com/trending?l=Mercury`
  }, {
    color: `#ff3670`,
    name: `Mermaid`,
    url: `https://github.com/trending?l=Mermaid`
  }, {
    color: `#007800`,
    name: `Meson`,
    url: `https://github.com/trending?l=Meson`
  }, {
    color: `#8f14e9`,
    name: `Metal`,
    url: `https://github.com/trending?l=Metal`
  }, {
    color: '#778899',
    name: `MiniD`,
    url: `https://github.com/trending?l=MiniD`
  }, {
    color: `#ff1111`,
    name: `MiniYAML`,
    url: `https://github.com/trending?l=MiniYAML`
  }, {
    color: `#02b046`,
    name: `Mint`,
    url: `https://github.com/trending?l=Mint`
  }, {
    color: `#c7a938`,
    name: `Mirah`,
    url: `https://github.com/trending?l=Mirah`
  }, {
    color: `#3d57c3`,
    name: `mIRC Script`,
    url: `https://github.com/trending?l=mIRC-Script`
  }, {
    color: `#5EC8DB`,
    name: `MLIR`,
    url: `https://github.com/trending?l=MLIR`
  }, {
    color: `#de1d31`,
    name: `Modelica`,
    url: `https://github.com/trending?l=Modelica`
  }, {
    color: `#10253f`,
    name: `Modula-2`,
    url: `https://github.com/trending?l=Modula-2`
  }, {
    color: `#223388`,
    name: `Modula-3`,
    url: `https://github.com/trending?l=Modula-3`
  }, {
    color: '#778899',
    name: `Module Management System`,
    url: `https://github.com/trending?l=Module-Management-System`
  }, {
    color: '#778899',
    name: `Monkey`,
    url: `https://github.com/trending?l=Monkey`
  }, {
    color: `#8D6747`,
    name: `Monkey C`,
    url: `https://github.com/trending?l=Monkey-C`
  }, {
    color: '#778899',
    name: `Moocode`,
    url: `https://github.com/trending?l=Moocode`
  }, {
    color: `#ff4585`,
    name: `MoonScript`,
    url: `https://github.com/trending?l=MoonScript`
  }, {
    color: `#fbb03b`,
    name: `Motoko`,
    url: `https://github.com/trending?l=Motoko`
  }, {
    color: `#005daa`,
    name: `Motorola 68K Assembly`,
    url: `https://github.com/trending?l=Motorola-68K-Assembly`
  }, {
    color: `#4a137a`,
    name: `Move`,
    url: `https://github.com/trending?l=Move`
  }, {
    color: `#62A8D6`,
    name: `MQL4`,
    url: `https://github.com/trending?l=MQL4`
  }, {
    color: `#4A76B8`,
    name: `MQL5`,
    url: `https://github.com/trending?l=MQL5`
  }, {
    color: `#b7e1f4`,
    name: `MTML`,
    url: `https://github.com/trending?l=MTML`
  }, {
    color: '#778899',
    name: `MUF`,
    url: `https://github.com/trending?l=MUF`
  }, {
    color: `#244963`,
    name: `mupad`,
    url: `https://github.com/trending?l=mupad`
  }, {
    color: `#724b3b`,
    name: `Mustache`,
    url: `https://github.com/trending?l=Mustache`
  }, {
    color: '#778899',
    name: `Myghty`,
    url: `https://github.com/trending?l=Myghty`
  }, {
    color: `#2d004d`,
    name: `nanorc`,
    url: `https://github.com/trending?l=nanorc`
  }, {
    color: `#1d2c4e`,
    name: `Nasal`,
    url: `https://github.com/trending?l=Nasal`
  }, {
    color: '#778899',
    name: `NASL`,
    url: `https://github.com/trending?l=NASL`
  }, {
    color: `#28431f`,
    name: `NCL`,
    url: `https://github.com/trending?l=NCL`
  }, {
    color: `#990000`,
    name: `Nearley`,
    url: `https://github.com/trending?l=Nearley`
  }, {
    color: `#3d3c6e`,
    name: `Nemerle`,
    url: `https://github.com/trending?l=Nemerle`
  }, {
    color: `#94B0C7`,
    name: `nesC`,
    url: `https://github.com/trending?l=nesC`
  }, {
    color: `#0aa0ff`,
    name: `NetLinx`,
    url: `https://github.com/trending?l=NetLinx`
  }, {
    color: `#747faa`,
    name: `NetLinx+ERB`,
    url: `https://github.com/trending?l=NetLinx+ERB`
  }, {
    color: `#ff6375`,
    name: `NetLogo`,
    url: `https://github.com/trending?l=NetLogo`
  }, {
    color: `#87AED7`,
    name: `NewLisp`,
    url: `https://github.com/trending?l=NewLisp`
  }, {
    color: `#3ac486`,
    name: `Nextflow`,
    url: `https://github.com/trending?l=Nextflow`
  }, {
    color: `#009639`,
    name: `Nginx`,
    url: `https://github.com/trending?l=Nginx`
  }, {
    color: `#ffc200`,
    name: `Nim`,
    url: `https://github.com/trending?l=Nim`
  }, {
    color: `#009917`,
    name: `Nit`,
    url: `https://github.com/trending?l=Nit`
  }, {
    color: `#7e7eff`,
    name: `Nix`,
    url: `https://github.com/trending?l=Nix`
  }, {
    color: `#cb3837`,
    name: `NPM Config`,
    url: `https://github.com/trending?l=NPM-Config`
  }, {
    color: '#778899',
    name: `NSIS`,
    url: `https://github.com/trending?l=NSIS`
  }, {
    color: `#c9df40`,
    name: `Nu`,
    url: `https://github.com/trending?l=Nu`
  }, {
    color: `#9C8AF9`,
    name: `NumPy`,
    url: `https://github.com/trending?l=NumPy`
  }, {
    color: `#3d8137`,
    name: `Nunjucks`,
    url: `https://github.com/trending?l=Nunjucks`
  }, {
    color: `#111522`,
    name: `NWScript`,
    url: `https://github.com/trending?l=NWScript`
  }, {
    color: `#85ea2d`,
    name: `OASv2-json`,
    url: `https://github.com/trending?l=OASv2-json`
  }, {
    color: `#85ea2d`,
    name: `OASv2-yaml`,
    url: `https://github.com/trending?l=OASv2-yaml`
  }, {
    color: `#85ea2d`,
    name: `OASv3-json`,
    url: `https://github.com/trending?l=OASv3-json`
  }, {
    color: `#85ea2d`,
    name: `OASv3-yaml`,
    url: `https://github.com/trending?l=OASv3-yaml`
  }, {
    color: `#438eff`,
    name: `Objective-C`,
    url: `https://github.com/trending?l=Objective-C`
  }, {
    color: `#6866fb`,
    name: `Objective-C++`,
    url: `https://github.com/trending?l=Objective-C++`
  }, {
    color: `#ff0c5a`,
    name: `Objective-J`,
    url: `https://github.com/trending?l=Objective-J`
  }, {
    color: `#424893`,
    name: `ObjectScript`,
    url: `https://github.com/trending?l=ObjectScript`
  }, {
    color: `#3be133`,
    name: `OCaml`,
    url: `https://github.com/trending?l=OCaml`
  }, {
    color: `#60AFFE`,
    name: `Odin`,
    url: `https://github.com/trending?l=Odin`
  }, {
    color: `#cabbff`,
    name: `Omgrofl`,
    url: `https://github.com/trending?l=Omgrofl`
  }, {
    color: `#b0b77e`,
    name: `ooc`,
    url: `https://github.com/trending?l=ooc`
  }, {
    color: '#778899',
    name: `Opa`,
    url: `https://github.com/trending?l=Opa`
  }, {
    color: `#f7ede0`,
    name: `Opal`,
    url: `https://github.com/trending?l=Opal`
  }, {
    color: `#7d9199`,
    name: `Open Policy Agent`,
    url: `https://github.com/trending?l=Open-Policy-Agent`
  }, {
    color: `#85ea2d`,
    name: `OpenAPI Specification v2`,
    url: `https://github.com/trending?l=OpenAPI-Specification-v2`
  }, {
    color: `#85ea2d`,
    name: `OpenAPI Specification v3`,
    url: `https://github.com/trending?l=OpenAPI-Specification-v3`
  }, {
    color: `#ed2e2d`,
    name: `OpenCL`,
    url: `https://github.com/trending?l=OpenCL`
  }, {
    color: `#5ce600`,
    name: `OpenEdge ABL`,
    url: `https://github.com/trending?l=OpenEdge-ABL`
  }, {
    color: `#AA70FF`,
    name: `OpenQASM`,
    url: `https://github.com/trending?l=OpenQASM`
  }, {
    color: '#778899',
    name: `OpenRC runscript`,
    url: `https://github.com/trending?l=OpenRC-runscript`
  }, {
    color: `#e5cd45`,
    name: `OpenSCAD`,
    url: `https://github.com/trending?l=OpenSCAD`
  }, {
    color: `#476732`,
    name: `Option List`,
    url: `https://github.com/trending?l=Option-List`
  }, {
    color: `#77aa99`,
    name: `Org`,
    url: `https://github.com/trending?l=Org`
  }, {
    color: '#778899',
    name: `Ox`,
    url: `https://github.com/trending?l=Ox`
  }, {
    color: `#cdd0e3`,
    name: `Oxygene`,
    url: `https://github.com/trending?l=Oxygene`
  }, {
    color: `#fab738`,
    name: `Oz`,
    url: `https://github.com/trending?l=Oz`
  }, {
    color: `#7055b5`,
    name: `P4`,
    url: `https://github.com/trending?l=P4`
  }, {
    color: `#cc0000`,
    name: `Pan`,
    url: `https://github.com/trending?l=Pan`
  }, {
    color: `#6600cc`,
    name: `Papyrus`,
    url: `https://github.com/trending?l=Papyrus`
  }, {
    color: `#f3ca0a`,
    name: `Parrot`,
    url: `https://github.com/trending?l=Parrot`
  }, {
    color: '#778899',
    name: `Parrot Assembly`,
    url: `https://github.com/trending?l=Parrot-Assembly`
  }, {
    color: '#778899',
    name: `Parrot Internal Representation`,
    url: `https://github.com/trending?l=Parrot-Internal-Representation`
  }, {
    color: `#E3F171`,
    name: `Pascal`,
    url: `https://github.com/trending?l=Pascal`
  }, {
    color: `#dbb284`,
    name: `Pawn`,
    url: `https://github.com/trending?l=Pawn`
  }, {
    color: `#0d00ff`,
    name: `PDDL`,
    url: `https://github.com/trending?l=PDDL`
  }, {
    color: `#234d6b`,
    name: `PEG.js`,
    url: `https://github.com/trending?l=PEG.js`
  }, {
    color: `#C76F5B`,
    name: `Pep8`,
    url: `https://github.com/trending?l=Pep8`
  }, {
    color: `#0298c3`,
    name: `Perl`,
    url: `https://github.com/trending?l=Perl`
  }, {
    color: `#4F5D95`,
    name: `PHP`,
    url: `https://github.com/trending?l=PHP`
  }, {
    color: `#6067af`,
    name: `PicoLisp`,
    url: `https://github.com/trending?l=PicoLisp`
  }, {
    color: `#fcd7de`,
    name: `PigLatin`,
    url: `https://github.com/trending?l=PigLatin`
  }, {
    color: `#005390`,
    name: `Pike`,
    url: `https://github.com/trending?l=Pike`
  }, {
    color: `#fbbd16`,
    name: `PlantUML`,
    url: `https://github.com/trending?l=PlantUML`
  }, {
    color: `#336790`,
    name: `PLpgSQL`,
    url: `https://github.com/trending?l=PLpgSQL`
  }, {
    color: `#dad8d8`,
    name: `PLSQL`,
    url: `https://github.com/trending?l=PLSQL`
  }, {
    color: `#d80074`,
    name: `PogoScript`,
    url: `https://github.com/trending?l=PogoScript`
  }, {
    color: `#ae81ff`,
    name: `Polar`,
    url: `https://github.com/trending?l=Polar`
  }, {
    color: '#778899',
    name: `Pony`,
    url: `https://github.com/trending?l=Pony`
  }, {
    color: `#f8bd00`,
    name: `Portugol`,
    url: `https://github.com/trending?l=Portugol`
  }, {
    color: `#dc3a0c`,
    name: `PostCSS`,
    url: `https://github.com/trending?l=PostCSS`
  }, {
    color: `#da291c`,
    name: `PostScript`,
    url: `https://github.com/trending?l=PostScript`
  }, {
    color: `#6bac65`,
    name: `POV-Ray SDL`,
    url: `https://github.com/trending?l=POV-Ray-SDL`
  }, {
    color: `#8f0f8d`,
    name: `PowerBuilder`,
    url: `https://github.com/trending?l=PowerBuilder`
  }, {
    color: `#012456`,
    name: `PowerShell`,
    url: `https://github.com/trending?l=PowerShell`
  }, {
    color: `#0c344b`,
    name: `Prisma`,
    url: `https://github.com/trending?l=Prisma`
  }, {
    color: `#0096D8`,
    name: `Processing`,
    url: `https://github.com/trending?l=Processing`
  }, {
    color: `#3B2F63`,
    name: `Procfile`,
    url: `https://github.com/trending?l=Procfile`
  }, {
    color: `#74283c`,
    name: `Prolog`,
    url: `https://github.com/trending?l=Prolog`
  }, {
    color: `#de0000`,
    name: `Promela`,
    url: `https://github.com/trending?l=Promela`
  }, {
    color: `#7fa2a7`,
    name: `Propeller Spin`,
    url: `https://github.com/trending?l=Propeller-Spin`
  }, {
    color: `#a86454`,
    name: `Pug`,
    url: `https://github.com/trending?l=Pug`
  }, {
    color: `#302B6D`,
    name: `Puppet`,
    url: `https://github.com/trending?l=Puppet`
  }, {
    color: `#5a6986`,
    name: `PureBasic`,
    url: `https://github.com/trending?l=PureBasic`
  }, {
    color: `#1D222D`,
    name: `PureScript`,
    url: `https://github.com/trending?l=PureScript`
  }, {
    color: `#ee1e10`,
    name: `Pyret`,
    url: `https://github.com/trending?l=Pyret`
  }, {
    color: `#3572A5`,
    name: `Python`,
    url: `https://github.com/trending?l=Python`
  }, {
    color: `#3572A5`,
    name: `Python console`,
    url: `https://github.com/trending?l=Python-console`
  }, {
    color: `#3572A5`,
    name: `Python traceback`,
    url: `https://github.com/trending?l=Python-traceback`
  }, {
    color: `#0040cd`,
    name: `q`,
    url: `https://github.com/trending?l=q`
  }, {
    color: `#fed659`,
    name: `Q#`,
    url: `https://github.com/trending?l=Qsharp`
  }, {
    color: '#778899',
    name: `QMake`,
    url: `https://github.com/trending?l=QMake`
  }, {
    color: `#44a51c`,
    name: `QML`,
    url: `https://github.com/trending?l=QML`
  }, {
    color: `#00b841`,
    name: `Qt Script`,
    url: `https://github.com/trending?l=Qt-Script`
  }, {
    color: `#882233`,
    name: `Quake`,
    url: `https://github.com/trending?l=Quake`
  }, {
    color: `#198CE7`,
    name: `R`,
    url: `https://github.com/trending?l=R`
  }, {
    color: `#3c5caa`,
    name: `Racket`,
    url: `https://github.com/trending?l=Racket`
  }, {
    color: `#9d5200`,
    name: `Ragel`,
    url: `https://github.com/trending?l=Ragel`
  }, {
    color: `#0000fb`,
    name: `Raku`,
    url: `https://github.com/trending?l=Raku`
  }, {
    color: `#77d9fb`,
    name: `RAML`,
    url: `https://github.com/trending?l=RAML`
  }, {
    color: `#fffaa0`,
    name: `Rascal`,
    url: `https://github.com/trending?l=Rascal`
  }, {
    color: `#701516`,
    name: `RDoc`,
    url: `https://github.com/trending?l=RDoc`
  }, {
    color: '#778899',
    name: `REALbasic`,
    url: `https://github.com/trending?l=REALbasic`
  }, {
    color: `#ff5847`,
    name: `Reason`,
    url: `https://github.com/trending?l=Reason`
  }, {
    color: `#ff5847`,
    name: `ReasonLIGO`,
    url: `https://github.com/trending?l=ReasonLIGO`
  }, {
    color: `#358a5b`,
    name: `Rebol`,
    url: `https://github.com/trending?l=Rebol`
  }, {
    color: `#0673ba`,
    name: `Record Jar`,
    url: `https://github.com/trending?l=Record-Jar`
  }, {
    color: `#f50000`,
    name: `Red`,
    url: `https://github.com/trending?l=Red`
  }, {
    color: '#778899',
    name: `Redcode`,
    url: `https://github.com/trending?l=Redcode`
  }, {
    color: `#009a00`,
    name: `Regular Expression`,
    url: `https://github.com/trending?l=Regular-Expression`
  }, {
    color: `#ff7f7f`,
    name: `Ren'Py`,
    url: `https://github.com/trending?l=Ren'Py`
  }, {
    color: '#778899',
    name: `RenderScript`,
    url: `https://github.com/trending?l=RenderScript`
  }, {
    color: `#ed5051`,
    name: `ReScript`,
    url: `https://github.com/trending?l=ReScript`
  }, {
    color: `#141414`,
    name: `reStructuredText`,
    url: `https://github.com/trending?l=reStructuredText`
  }, {
    color: `#d90e09`,
    name: `REXX`,
    url: `https://github.com/trending?l=REXX`
  }, {
    color: `#2D54CB`,
    name: `Ring`,
    url: `https://github.com/trending?l=Ring`
  }, {
    color: `#A71E49`,
    name: `Riot`,
    url: `https://github.com/trending?l=Riot`
  }, {
    color: `#198ce7`,
    name: `RMarkdown`,
    url: `https://github.com/trending?l=RMarkdown`
  }, {
    color: `#00c0b5`,
    name: `RobotFramework`,
    url: `https://github.com/trending?l=RobotFramework`
  }, {
    color: `#ecdebe`,
    name: `Roff`,
    url: `https://github.com/trending?l=Roff`
  }, {
    color: `#ecdebe`,
    name: `Roff Manpage`,
    url: `https://github.com/trending?l=Roff-Manpage`
  }, {
    color: `#cc0088`,
    name: `Rouge`,
    url: `https://github.com/trending?l=Rouge`
  }, {
    color: `#DE3941`,
    name: `RouterOS Script`,
    url: `https://github.com/trending?l=RouterOS-Script`
  }, {
    color: '#778899',
    name: `RPC`,
    url: `https://github.com/trending?l=RPC`
  }, {
    color: `#2BDE21`,
    name: `RPGLE`,
    url: `https://github.com/trending?l=RPGLE`
  }, {
    color: `#701516`,
    name: `Ruby`,
    url: `https://github.com/trending?l=Ruby`
  }, {
    color: `#665a4e`,
    name: `RUNOFF`,
    url: `https://github.com/trending?l=RUNOFF`
  }, {
    color: `#dea584`,
    name: `Rust`,
    url: `https://github.com/trending?l=Rust`
  }, {
    color: '#778899',
    name: `Sage`,
    url: `https://github.com/trending?l=Sage`
  }, {
    color: `#646464`,
    name: `SaltStack`,
    url: `https://github.com/trending?l=SaltStack`
  }, {
    color: `#B34936`,
    name: `SAS`,
    url: `https://github.com/trending?l=SAS`
  }, {
    color: `#a53b70`,
    name: `Sass`,
    url: `https://github.com/trending?l=Sass`
  }, {
    color: `#c22d40`,
    name: `Scala`,
    url: `https://github.com/trending?l=Scala`
  }, {
    color: `#bd181a`,
    name: `Scaml`,
    url: `https://github.com/trending?l=Scaml`
  }, {
    color: `#fdc700`,
    name: `Scenic`,
    url: `https://github.com/trending?l=Scenic`
  }, {
    color: `#1e4aec`,
    name: `Scheme`,
    url: `https://github.com/trending?l=Scheme`
  }, {
    color: `#ca0f21`,
    name: `Scilab`,
    url: `https://github.com/trending?l=Scilab`
  }, {
    color: `#c6538c`,
    name: `SCSS`,
    url: `https://github.com/trending?l=SCSS`
  }, {
    color: `#64b970`,
    name: `sed`,
    url: `https://github.com/trending?l=sed`
  }, {
    color: `#0579aa`,
    name: `Self`,
    url: `https://github.com/trending?l=Self`
  }, {
    color: `#222c37`,
    name: `ShaderLab`,
    url: `https://github.com/trending?l=ShaderLab`
  }, {
    color: `#89e051`,
    name: `Shell`,
    url: `https://github.com/trending?l=Shell`
  }, {
    color: `#cecfcb`,
    name: `ShellCheck Config`,
    url: `https://github.com/trending?l=ShellCheck-Config`
  }, {
    color: '#778899',
    name: `ShellSession`,
    url: `https://github.com/trending?l=ShellSession`
  }, {
    color: `#120F14`,
    name: `Shen`,
    url: `https://github.com/trending?l=Shen`
  }, {
    color: '#778899',
    name: `Sieve`,
    url: `https://github.com/trending?l=Sieve`
  }, {
    color: `#C9BFED`,
    name: `Simple File Verification`,
    url: `https://github.com/trending?l=Simple-File-Verification`
  }, {
    color: `#64E6AD`,
    name: `Singularity`,
    url: `https://github.com/trending?l=Singularity`
  }, {
    color: `#007eff`,
    name: `Slash`,
    url: `https://github.com/trending?l=Slash`
  }, {
    color: `#003fa2`,
    name: `Slice`,
    url: `https://github.com/trending?l=Slice`
  }, {
    color: `#2b2b2b`,
    name: `Slim`,
    url: `https://github.com/trending?l=Slim`
  }, {
    color: '#778899',
    name: `Smali`,
    url: `https://github.com/trending?l=Smali`
  }, {
    color: `#596706`,
    name: `Smalltalk`,
    url: `https://github.com/trending?l=Smalltalk`
  }, {
    color: `#f0c040`,
    name: `Smarty`,
    url: `https://github.com/trending?l=Smarty`
  }, {
    color: `#c44536`,
    name: `Smithy`,
    url: `https://github.com/trending?l=Smithy`
  }, {
    color: `#c94949`,
    name: `SmPL`,
    url: `https://github.com/trending?l=SmPL`
  }, {
    color: '#778899',
    name: `SMT`,
    url: `https://github.com/trending?l=SMT`
  }, {
    color: `#AA6746`,
    name: `Solidity`,
    url: `https://github.com/trending?l=Solidity`
  }, {
    color: `#f69e1d`,
    name: `SourcePawn`,
    url: `https://github.com/trending?l=SourcePawn`
  }, {
    color: `#0C4597`,
    name: `SPARQL`,
    url: `https://github.com/trending?l=SPARQL`
  }, {
    color: `#3F3F3F`,
    name: `SQF`,
    url: `https://github.com/trending?l=SQF`
  }, {
    color: `#e38c00`,
    name: `SQL`,
    url: `https://github.com/trending?l=SQL`
  }, {
    color: `#e38c00`,
    name: `SQLPL`,
    url: `https://github.com/trending?l=SQLPL`
  }, {
    color: `#800000`,
    name: `Squirrel`,
    url: `https://github.com/trending?l=Squirrel`
  }, {
    color: `#348a34`,
    name: `SRecode Template`,
    url: `https://github.com/trending?l=SRecode-Template`
  }, {
    color: `#b2011d`,
    name: `Stan`,
    url: `https://github.com/trending?l=Stan`
  }, {
    color: `#dc566d`,
    name: `Standard ML`,
    url: `https://github.com/trending?l=Standard-ML`
  }, {
    color: `#76d275`,
    name: `Starlark`,
    url: `https://github.com/trending?l=Starlark`
  }, {
    color: `#1a5f91`,
    name: `Stata`,
    url: `https://github.com/trending?l=Stata`
  }, {
    color: `#373b5e`,
    name: `STL`,
    url: `https://github.com/trending?l=STL`
  }, {
    color: `#3fb34f`,
    name: `StringTemplate`,
    url: `https://github.com/trending?l=StringTemplate`
  }, {
    color: `#ff6347`,
    name: `Stylus`,
    url: `https://github.com/trending?l=Stylus`
  }, {
    color: `#9e0101`,
    name: `SubRip Text`,
    url: `https://github.com/trending?l=SubRip-Text`
  }, {
    color: `#2fcc9f`,
    name: `SugarSS`,
    url: `https://github.com/trending?l=SugarSS`
  }, {
    color: `#46390b`,
    name: `SuperCollider`,
    url: `https://github.com/trending?l=SuperCollider`
  }, {
    color: `#ff3e00`,
    name: `Svelte`,
    url: `https://github.com/trending?l=Svelte`
  }, {
    color: `#ff9900`,
    name: `SVG`,
    url: `https://github.com/trending?l=SVG`
  }, {
    color: `#F05138`,
    name: `Swift`,
    url: `https://github.com/trending?l=Swift`
  }, {
    color: '#778899',
    name: `SWIG`,
    url: `https://github.com/trending?l=SWIG`
  }, {
    color: `#DAE1C2`,
    name: `SystemVerilog`,
    url: `https://github.com/trending?l=SystemVerilog`
  }, {
    color: `#333333`,
    name: `Talon`,
    url: `https://github.com/trending?l=Talon`
  }, {
    color: `#e4cc98`,
    name: `Tcl`,
    url: `https://github.com/trending?l=Tcl`
  }, {
    color: '#778899',
    name: `Tcsh`,
    url: `https://github.com/trending?l=Tcsh`
  }, {
    color: `#00004c`,
    name: `Terra`,
    url: `https://github.com/trending?l=Terra`
  }, {
    color: `#3D6117`,
    name: `TeX`,
    url: `https://github.com/trending?l=TeX`
  }, {
    color: `#ffe7ac`,
    name: `Textile`,
    url: `https://github.com/trending?l=Textile`
  }, {
    color: `#df66e4`,
    name: `TextMate Properties`,
    url: `https://github.com/trending?l=TextMate-Properties`
  }, {
    color: `#D12127`,
    name: `Thrift`,
    url: `https://github.com/trending?l=Thrift`
  }, {
    color: `#A0AA87`,
    name: `TI Program`,
    url: `https://github.com/trending?l=TI-Program`
  }, {
    color: `#4b0079`,
    name: `TLA`,
    url: `https://github.com/trending?l=TLA`
  }, {
    color: `#9c4221`,
    name: `TOML`,
    url: `https://github.com/trending?l=TOML`
  }, {
    color: `#e38c00`,
    name: `TSQL`,
    url: `https://github.com/trending?l=TSQL`
  }, {
    color: `#237346`,
    name: `TSV`,
    url: `https://github.com/trending?l=TSV`
  }, {
    color: `#3178c6`,
    name: `TSX`,
    url: `https://github.com/trending?l=TSX`
  }, {
    color: `#cf142b`,
    name: `Turing`,
    url: `https://github.com/trending?l=Turing`
  }, {
    color: `#c1d026`,
    name: `Twig`,
    url: `https://github.com/trending?l=Twig`
  }, {
    color: `#0178b8`,
    name: `TXL`,
    url: `https://github.com/trending?l=TXL`
  }, {
    color: `#3178c6`,
    name: `TypeScript`,
    url: `https://github.com/trending?l=TypeScript`
  }, {
    color: `#4e3617`,
    name: `Unified Parallel C`,
    url: `https://github.com/trending?l=Unified-Parallel-C`
  }, {
    color: `#222c37`,
    name: `Unity3D Asset`,
    url: `https://github.com/trending?l=Unity3D-Asset`
  }, {
    color: '#778899',
    name: `Unix Assembly`,
    url: `https://github.com/trending?l=Unix-Assembly`
  }, {
    color: `#9933cc`,
    name: `Uno`,
    url: `https://github.com/trending?l=Uno`
  }, {
    color: `#a54c4d`,
    name: `UnrealScript`,
    url: `https://github.com/trending?l=UnrealScript`
  }, {
    color: `#ccccee`,
    name: `UrWeb`,
    url: `https://github.com/trending?l=UrWeb`
  }, {
    color: `#4f87c4`,
    name: `V`,
    url: `https://github.com/trending?l=V`
  }, {
    color: `#a56de2`,
    name: `Vala`,
    url: `https://github.com/trending?l=Vala`
  }, {
    color: `#f26025`,
    name: `Valve Data Format`,
    url: `https://github.com/trending?l=Valve-Data-Format`
  }, {
    color: `#867db1`,
    name: `VBA`,
    url: `https://github.com/trending?l=VBA`
  }, {
    color: `#15dcdc`,
    name: `VBScript`,
    url: `https://github.com/trending?l=VBScript`
  }, {
    color: `#148AA8`,
    name: `VCL`,
    url: `https://github.com/trending?l=VCL`
  }, {
    color: `#507cff`,
    name: `Velocity Template Language`,
    url: `https://github.com/trending?l=Velocity-Template-Language`
  }, {
    color: `#b2b7f8`,
    name: `Verilog`,
    url: `https://github.com/trending?l=Verilog`
  }, {
    color: `#adb2cb`,
    name: `VHDL`,
    url: `https://github.com/trending?l=VHDL`
  }, {
    color: `#199f4b`,
    name: `Vim Help File`,
    url: `https://github.com/trending?l=Vim-Help-File`
  }, {
    color: `#199f4b`,
    name: `Vim Script`,
    url: `https://github.com/trending?l=Vim-Script`
  }, {
    color: `#199f4b`,
    name: `Vim Snippet`,
    url: `https://github.com/trending?l=Vim-Snippet`
  }, {
    color: `#945db7`,
    name: `Visual Basic .NET`,
    url: `https://github.com/trending?l=Visual-Basic-.NET`
  }, {
    color: `#2c6353`,
    name: `Visual Basic 6.0`,
    url: `https://github.com/trending?l=Visual-Basic-6.0`
  }, {
    color: `#1F1F1F`,
    name: `Volt`,
    url: `https://github.com/trending?l=Volt`
  }, {
    color: `#41b883`,
    name: `Vue`,
    url: `https://github.com/trending?l=Vue`
  }, {
    color: `#2980b9`,
    name: `Vyper`,
    url: `https://github.com/trending?l=Vyper`
  }, {
    color: `#42f1f4`,
    name: `wdl`,
    url: `https://github.com/trending?l=wdl`
  }, {
    color: `#5b70bd`,
    name: `Web Ontology Language`,
    url: `https://github.com/trending?l=Web-Ontology-Language`
  }, {
    color: `#04133b`,
    name: `WebAssembly`,
    url: `https://github.com/trending?l=WebAssembly`
  }, {
    color: '#778899',
    name: `WebIDL`,
    url: `https://github.com/trending?l=WebIDL`
  }, {
    color: `#d5c397`,
    name: `Whiley`,
    url: `https://github.com/trending?l=Whiley`
  }, {
    color: `#fc5757`,
    name: `Wikitext`,
    url: `https://github.com/trending?l=Wikitext`
  }, {
    color: `#52d5ff`,
    name: `Windows Registry Entries`,
    url: `https://github.com/trending?l=Windows-Registry-Entries`
  }, {
    color: `#7582D1`,
    name: `wisp`,
    url: `https://github.com/trending?l=wisp`
  }, {
    color: `#ff0000`,
    name: `Witcher Script`,
    url: `https://github.com/trending?l=Witcher-Script`
  }, {
    color: `#a23738`,
    name: `Wollok`,
    url: `https://github.com/trending?l=Wollok`
  }, {
    color: `#f7e43f`,
    name: `World of Warcraft Addon Data`,
    url: `https://github.com/trending?l=World-of-Warcraft-Addon-Data`
  }, {
    color: `#383838`,
    name: `Wren`,
    url: `https://github.com/trending?l=Wren`
  }, {
    color: `#4B6BEF`,
    name: `X10`,
    url: `https://github.com/trending?l=X10`
  }, {
    color: `#403a40`,
    name: `xBase`,
    url: `https://github.com/trending?l=xBase`
  }, {
    color: `#99DA07`,
    name: `XC`,
    url: `https://github.com/trending?l=XC`
  }, {
    color: `#0060ac`,
    name: `XML`,
    url: `https://github.com/trending?l=XML`
  }, {
    color: `#0060ac`,
    name: `XML Property List`,
    url: `https://github.com/trending?l=XML-Property-List`
  }, {
    color: `#81bd41`,
    name: `Xojo`,
    url: `https://github.com/trending?l=Xojo`
  }, {
    color: `#285EEF`,
    name: `Xonsh`,
    url: `https://github.com/trending?l=Xonsh`
  }, {
    color: '#778899',
    name: `XProc`,
    url: `https://github.com/trending?l=XProc`
  }, {
    color: `#5232e7`,
    name: `XQuery`,
    url: `https://github.com/trending?l=XQuery`
  }, {
    color: '#778899',
    name: `XS`,
    url: `https://github.com/trending?l=XS`
  }, {
    color: `#EB8CEB`,
    name: `XSLT`,
    url: `https://github.com/trending?l=XSLT`
  }, {
    color: `#24255d`,
    name: `Xtend`,
    url: `https://github.com/trending?l=Xtend`
  }, {
    color: `#4B6C4B`,
    name: `Yacc`,
    url: `https://github.com/trending?l=Yacc`
  }, {
    color: `#cb171e`,
    name: `YAML`,
    url: `https://github.com/trending?l=YAML`
  }, {
    color: `#220000`,
    name: `YARA`,
    url: `https://github.com/trending?l=YARA`
  }, {
    color: `#32AB90`,
    name: `YASnippet`,
    url: `https://github.com/trending?l=YASnippet`
  }, {
    color: `#794932`,
    name: `Yul`,
    url: `https://github.com/trending?l=Yul`
  }, {
    color: `#0d665e`,
    name: `ZAP`,
    url: `https://github.com/trending?l=ZAP`
  }, {
    color: '#778899',
    name: `Zeek`,
    url: `https://github.com/trending?l=Zeek`
  }, {
    color: `#00BCD1`,
    name: `ZenScript`,
    url: `https://github.com/trending?l=ZenScript`
  }, {
    color: `#118f9e`,
    name: `Zephir`,
    url: `https://github.com/trending?l=Zephir`
  }, {
    color: `#ec915c`,
    name: `Zig`,
    url: `https://github.com/trending?l=Zig`
  }, {
    color: `#dc75e5`,
    name: `ZIL`,
    url: `https://github.com/trending?l=ZIL`
  }, {
    color: `#d67711`,
    name: `Zimpl`,
    url: `https://github.com/trending?l=Zimpl`
  }
];
